title: Albert Tamakloe
logo: "/images/yourface.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Web Developer specializing in React development.
  <br><br>
  Located in Houston, Texas
  <br><br>
  <a href="https://www.linkedin.com/in/alberttamakloe//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
